steps:
- id: 'Change Deployment Image Tag Name & Trigger cloud deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: 
  - '-c'
  - |
    ImageDigest="$(gcloud container images list-tags --format='get(digest)' ${_IMAGE_PATH} | head -1)"
    echo "Image Digest: ${ImageDigest}"
    sed "s/replace/${ImageDigest}/g" k8s-slsa-pod.yaml
    sed "s/SHORT_SHA/${SHORT_SHA}/g" k8s-slsa-pod.yaml
    gcloud beta deploy releases create rev-${SHORT_SHA} --delivery-pipeline=slsa-node-example-pipeline --labels=version=${SHORT_SHA} --region ${_KMS_KEY_LOCATION}
substitutions:
  _IMAGE_PATH: gcr.io/slsa-demo/sample-node
  _KMS_KEY_LOCATION: asia-east1