apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-deployment
spec:
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: asia-east1-docker.pkg.dev/slsa-demo/slsa-demo/juiceshop
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000

